name: GPR release
on:
  release:
    types: [created]

jobs:
  gpr:
    name: GPR
    uses: ./.github/workflows/template-release-all.yml
    with:
      registry-url: https://npm.pkg.github.com/

    secrets:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
