name: "<template-release-pkg>"
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

      registry-url:
        default: https://registry.npmjs.org
        required: false
        type: string

    secrets:
      AUTH_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Cloning source code
        uses: actions/checkout@v5
      - name: Configuring Node.js 22 (LTS)
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: ${{ inputs.registry-url }}

      - if: ${{ github.event.release.prerelease == true }}
        name: Publishing pre-release package
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      - if: ${{ github.event.release.prerelease == false }}
        name: Publishing latest package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
